import numpy as np
import cv2
import torch
from PIL import Image
import random
import os


def mask_on_image(mask: np.ndarray, img: np.ndarray, alpha: float = 0.5) -> np.ndarray:
    """
    Overlay an XAI mask on the original image.

    Args:
        mask (numpy.ndarray): The XAI-CAM mask.
        img (numpy.ndarray): The original image.
        alpha (float, optional): The transparency of the mask overlay. Default is 0.5.

    Returns:
        numpy.ndarray: The image with the XAI-CAM mask overlayed.
    """
    heatmap = get_rgb_heatmap(mask)
    img = img.squeeze()
    cam_on_img = (1 - alpha) * img + alpha * heatmap
    return np.copy(cam_on_img)

def get_rgb_heatmap(mask: np.ndarray) -> np.ndarray:
    """Convert mask to RGB heatmap."""
    heatmap = cv2.applyColorMap(np.uint8(255 * mask), cv2.COLORMAP_JET)
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
    heatmap = np.float32(heatmap) / 255
    return np.copy(heatmap)

def normalize_image(img: np.ndarray) -> np.ndarray:
    """Normalize image values to [0, 1]."""
    return np.nan_to_num((img-img.min())/(img.max()-img.min()), nan=0.0, posinf=0.0,neginf=0.0)

def setup_environment(seed: int) -> torch.device:
    """
    Set up the environment for reproducibility and specify the device (GPU or CPU).

    Args:
        seed (int): The seed value for random number generation, ensuring reproducibility.

    Returns:
        device (torch.device): The device (either GPU or CPU) to run the model on.
    """
    torch.manual_seed(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print("Using device:", device)
    return device

def prepare_categories_and_images(image_path: str) -> tuple[list[str], dict[str, int], dict[str, list[str]]]:
    """
    Prepare categories and image file lists for each category in the dataset.

    Args:
        image_path (str): Path to the root directory of images.

    Returns:
        categories (list): List of category names (subdirectories in the image path).
        label_idx_dict (dict): A dictionary mapping category names to indices.
        imagedict (dict): A dictionary mapping categories to lists of image filenames.
    """
    categories = sorted(os.listdir(image_path))
    label_idx_dict = {cat: idx for idx, cat in enumerate(categories)}
    imagedict = {cat: os.listdir(os.path.join(image_path, cat)) for cat in categories}
    return categories, label_idx_dict, imagedict

def create_output_directories(output_path: str, categories: list[str]) -> None:
    """
    Create the necessary output directories to store the results.

    Args:
        output_path (str): The root directory where results will be saved.
        categories (list): List of category names for which to create subdirectories.
    """
    os.makedirs(output_path, exist_ok=True)
    for category in categories:
        for output_type in ["mask", "mask_on_image"]:
            os.makedirs(os.path.join(output_path, category, output_type), exist_ok=True)


def save_xai_outputs(mask: np.ndarray, original_image: np.ndarray, category: str, image_name: str, output_path: str) -> None:
    """
    General function to save the mask and overlay image generated by any XAI method.

    Args:
        mask (numpy.ndarray): The mask to save.
        original_image (numpy.ndarray): The original image to overlay the mask on.
        category (str): The category of the image.
        image_name (str): The filename of the image.
        output_path (str): Path to save the outputs.
    """
    mask = normalize_image(mask)
    overlay_image = mask_on_image(mask, normalize_image(original_image), alpha=0.3)
    overlay_image = (overlay_image * 255).astype(np.uint8)

    mask_path = os.path.join(output_path, category, "mask", image_name)
    overlay_path = os.path.join(output_path, category, "mask_on_image", image_name)

    np.save(mask_path, mask)
    Image.fromarray(overlay_image).save(overlay_path, "PNG")

def load_checkpoint(filepath: str, model: torch.nn.Module, optimizer: torch.optim.Optimizer, scheduler: torch.optim.lr_scheduler) -> tuple[int, dict]:
    """
    Load a model checkpoint from the specified file and restore model, optimizer, and scheduler states.

    Args:
        filepath (str): Path to the checkpoint file.
        model (torch.nn.Module): The model to load the state_dict into.
        optimizer (torch.optim.Optimizer): The optimizer to load the state_dict into.
        scheduler (torch.optim.lr_scheduler): The scheduler to load the state_dict into.

    Returns:
        epoch (int): The epoch the model was at when the checkpoint was saved.
        trainstats (dict): The training statistics stored in the checkpoint.
    """
    checkpoint = torch.load(filepath, map_location=torch.device('cpu'))
    model.load_state_dict(checkpoint['model'])
    optimizer.load_state_dict(checkpoint['optimizer'])
    scheduler.load_state_dict(checkpoint['scheduler'])
    return checkpoint['epoch'], checkpoint['trainstats']



#get a cutout based on a cutoff value
def get_cutoff_area(mask,img,cutoff = 0.5):
    for i in range(3):
        img[:,:,i] = np.where(mask>cutoff,img[:,:,i],0)
    return np.copy(img)

#get a cutout based on a percentage value.
def get_percentage_of_image(image,mask,percentage, fill_value = 0.0):
    masked_image = np.zeros_like(image)
    n = mask.size
    sortedvalues = np.sort(mask.flatten('K'))[::-1]
    
    index = int(n/100*percentage)
    index_2 = n//100*percentage
    cutoff = sortedvalues[index]
    for i in range(3):
        masked_image[:,:,i] = np.where(mask-cutoff>0.0,image[:,:,i],fill_value)
    return masked_image


def get_percentage_of_image_1d(image,mask,percentage, fill_value = 0.0):
    image = normalize_image(image)
    mask = normalize_image(mask)
    masked_image = np.zeros_like(image)
    n = mask.size
    sortedvalues = np.sort(mask.flatten('K'))[::-1]
    
    index = int(n/100*percentage)
    index_2 = n//100*percentage
    cutoff = sortedvalues[index]
    for i in range(3):
        masked_image = np.where(mask-cutoff>0.0,image,fill_value)
    return masked_image


def get_input_tensors(image):
    return transform_test(image).unsqueeze(0)


def get_contained_part(mask1,mask2):
    mask1,mask2 = normalize_image(mask1),normalize_image(mask2)
    return np.array((mask1 == 1.0) & (mask2 == 1.0))
    